# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Chef Clientの最新版を利用可能にする
  config.omnibus.chef_version = :latest

  config.vm.box = "centos65_php"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.5-x86_64-v20140110.box"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = [ "cookbooks", "site-cookbooks" ]

    chef.run_list = %w[
      recipe[yum]
      recipe[yum-epel]
      recipe[yum-ius]
      recipe[php]
    ]
  end

end
